### ISSUE TITLE
Does not find matched engine: pc_xvfb.

### ISSUE THREAD

**Issue by Aquarian-Age** [VincentWei/build-minigui-4.0#1]
NEWGAL>PCXVFB: Wait too long for CLIENT.
NEWGAL: Does not find matched engine: pc_xvfb.
KERNEL>InitGUI: Can not get graphics engine information!

ubuntu18.04 LTS
编译之后无法运行

**Comment by VincentWei** [comment]
Please run $./build-deps.sh first to install gvfb.
