### ISSUE TITLE
I found a small mistake. I don't know if you know it

### ISSUE THREAD

**Issue by CaoZewei** [VincentWei/build-minigui-4.0#4]
I found that you misspelled cplasplus in the ncs-window.h  and wrote cplaspus。And  Every time I modify it, it changes after I save it。

**Comment by CaoZewei** [comment]
Im misspelled too ,I mean Cplusplus but you wrote Cpluspus. missing l

**Comment by VincentWei** [comment]
Fix! Thanks for your report!
